### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by RobsonVinicius** [RobsonVinicius/php-mysql-parte1#1]
- [x] 1. Primeiros passos com PHP
     - [x] PHP, a sintaxe básica I
     - [x] Praticando a sintaxe I 
     - [x] PHP, a sintaxe básica II
     - [x] Praticando a sintaxe II
     - [x] Instando o XAMPP e o Sublime
     - [x] Criando o primeiro HTML
     - [x] Primeira versão do adiciona-produto
     - [x] Exibindo o preço
     - [x] Criando o formulário 
     - [x] Cabeçalho e rodapé 
     - [x] Fazendo Contas
     - [x] Código devolvido ao cliente
- [x] 2. Inserindo produtos no banco de dados
     - [x] Inserindo produtos no banco de dados
     - [x] Criando a tabela de produtos
     - [x] Inserindo no banco de dados
     - [x] Fechando a conexão 
     - [x] O "i" nos métodos
- [x] 3. Criando Funções no PHP
     - [x] Criando a primeira função
     - [x] Usando a função 
     - [x] Colocando menus
     - [x] Melhorando o formulário
     - [x] mysqli_error
     - [x] Muitas funções?   
        - [x] Verificar conexão com o Banco de Dados Online
- [x] 4. Listando todos os produtos
     - [x] Listando os produtos (aula)
     - [x] conecta.php
     - [x] Inclua nos outros arquivos
     - [x] Listando os produtos
     - [x] Isolando a conexão
- [x] 5. Melhorando a listagem de produtos
     - [x] Melhorando a listagem de produtos (aula)
     - [x] Função de Lista Produtos
     - [x] banco-produto.php
     - [x] Melhorando a listagem de produto
     - [x] Fechando o foreach
- [x] 6. Deletando produtos
     - [x] Link de remoção 
     - [x] Remover produto
     - [x] Removendo o produto
     - [x] Redirecionamento 
     - [x] Exibindo msg de deleção 
     - [x] iguais
- [x] 7. Entendendo a diferença entre GET e POST
     - [x] Entendendo a diferenção entre GET e POST
     - [x] Criando a coluna no banco de dados
     - [x] Adicionando descrição 
     - [x] Exibindo a descrição na listagem 
     - [x] Deleção e inserção virando POST 
     - [x] GET e POST
- [x] 8. Relacionando Produtos com Categorias
     - [x] Relacionando Produtos com Categorias
     - [x] Criando a tabela de Categorias
     - [x] Criando a chave estrangeira
     - [x] banco-categoria
     - [x] Exibindo as categorias
     - [x] Mudando a inserção 
     - [x] Pegando a categoria na lista de produtos
     - [x] Exibindo a categoria na listagem
- [x] 9. Lidando com Selects e Checkboxes
     - [x] Lidando com Selects e Checkboxes
     - [x] Usando select
     - [x] Coluna de usado 
     - [x] Usando checkbox
     - [x] Checkbox, radios e select
- [x] 10. Alterando produtos
     - [x] Alterando produtos
     - [x] Link de alterar
     - [x] Busca produto
     - [x] Altera produto
     - [x] Formulário de alteração
     - [x] Ação de alteração
     - [x] Similaridades
- [x] 11. Subindo a aplicação para um servidor
     - [x] Subindo a aplicação para um servidor
     - [x] Deploy
     - [x] Cloud de PHP

**Comment by RobsonVinicius** [comment]
Finalizando
